### ISSUE TITLE
Problem with npm start / npm run build - bundle.js missing

### ISSUE THREAD

**Issue by svpn** [stripe/stripe-billing-typographic#17]
Problem with bundle.js when trying to run npm start and npm run build.

```
server$ npm run build

typographic@1.0.0 build /home/ubuntu/stripe-billing-typographic
rollup -c

client/src/main.js → client/assets/bundle.js...
[!] (VuePlugin plugin) Error: tag <div> has no matching end tag.
client/src/components/Pricing.vue
Error: tag <div> has no matching end tag.
    at error (/home/ubuntu/stripe-billing-typographic/node_modules/rollup/dist/rollup.js:224:15)
    at /home/ubuntu/stripe-billing-typographic/node_modules/rollup/dist/rollup.js:17213:17
    at <anonymous>


npm ERR! Linux 4.15.0-1034-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! typographic@1.0.0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typographic@1.0.0 build script 'rollup -c'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the typographic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rollup -c
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs typographic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls typographic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/stripe-billing-typographic/server/npm-debug.log
```
**npm-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle typographic@1.0.0~prebuild: typographic@1.0.0
6 silly lifecycle typographic@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle typographic@1.0.0~build: typographic@1.0.0
8 verbose lifecycle typographic@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle typographic@1.0.0~build: PATH: /usr/share/npm/bin/node-gyp-bin:/home/ubuntu/stripe-billing-typographic/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sb$
10 verbose lifecycle typographic@1.0.0~build: CWD: /home/ubuntu/stripe-billing-typographic
11 silly lifecycle typographic@1.0.0~build: Args: [ '-c', 'rollup -c' ]
12 silly lifecycle typographic@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle typographic@1.0.0~build: Failed to exec build script
14 verbose stack Error: typographic@1.0.0 build: `rollup -c`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid typographic@1.0.0
16 verbose cwd /home/ubuntu/stripe-billing-typographic/server
17 error Linux 4.15.0-1034-aws
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error typographic@1.0.0 build: `rollup -c`
22 error Exit status 1
23 error Failed at the typographic@1.0.0 build script 'rollup -c'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the typographic package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     rollup -c
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs typographic
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls typographic
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ctrudeau-stripe** [comment]
Looks like this was [fixed here](https://github.com/stripe/stripe-billing-typographic/pull/18)
